export const texts = {
  cli: {
    description: "Show Claude Code sessions as a pixel-art village in the browser",
    startDescription: "Start the local server",
    portOptionDescription: "Port to listen on",
    installDescription: "Register Claude Code hooks in ~/.claude/settings.json",
    uninstallDescription: "Remove the hooks this tool registered",
    serverStarted: (address: string): string => `Server started: ${address}`,
    installApplied: (settingsPath: string): string => `Hooks installed in ${settingsPath}`,
    installNoChanges: (): string => "Hooks already up to date",
    uninstallRemoved: (settingsPath: string): string => `Hooks removed from ${settingsPath}`,
    uninstallNothingToRemove: (): string => "No claude-village hooks found",
    portInUse: (port: number): string => `Port ${port} is already in use, try a different one with --port`,
    serverStartFailed: (message: string): string => `Server failed to start: ${message}`,
    invalidSettingsJson: (settingsPath: string): string => `${settingsPath} contains invalid JSON, nothing changed`,
  },
  client: {
    title: "CLAUDE VILLAGE",
    resourceLabel: {
      stone: "STONE",
      wood: "WOOD",
      fish: "FISH",
    },
    resourceCounter: (label: string, value: number): string => `${label} ${value}`,
    soundName: "SOUND",
    alertsName: "ALERTS",
    on: "ON",
    off: "OFF",
    notificationTitle: "Claude Village",
    notificationBody: (projectName: string): string => `${projectName} needs attention`,
    sessionsTitle: "SESSIONS",
    settingsLabel: "SETTINGS",
    togglePanelLabel: "Toggle sessions panel",
    collapseGlyph: "«",
    expandGlyph: "»",
    tooltip: {
      status: {
        needsPermission: "waiting for permission",
        needsReply: "waiting for reply",
        resting: "resting on the spot",
        working: "working",
        idle: "idle at spot",
      },
      lastEvent: (ago: string): string => `last event ${ago} ago`,
      elapsed: {
        seconds: (value: number): string => `${value}s`,
        minutes: (value: number): string => `${value}m`,
        hours: (value: number): string => `${value}h`,
      },
    },
  },
};
